### ISSUE TITLE
Database tables are missing prefix

### ISSUE THREAD

**Issue by molwells** [gathercontent/craft-integration#2]
DB tables are being created without the proper prefix (i.e. `gathercontent_mapping` instead of `craft_gathercontent_mapping`). May need to replace string values with with Yii’s `{{%gathercontent_mapping}}` syntax.

**Comment by caleuanhopkins** [comment]
Yup having the same problem with the latest version of Craft and Gather Content plugin. Installed Craft through Composer:
<img width="1059" alt="screen shot 2018-05-09 at 16 06 59" src="https://user-images.githubusercontent.com/1164525/39822682-1d2941a6-53a3-11e8-94df-bb7aba47252c.png">
<img width="374" alt="screen shot 2018-05-09 at 16 07 05" src="https://user-images.githubusercontent.com/1164525/39822683-1d45cd08-53a3-11e8-99f1-de9309ce8319.png">

**Comment by valery-solspace** [comment]
Thanks for the feedback! Should be fixed in latest version v1.0.7
