### ISSUE TITLE
Can't map to Redactor field type

### ISSUE THREAD

**Issue by evanwarner** [gathercontent/craft-integration#3]
Despite the [claim that the plugin supports](http://help.gathercontent.com/importing-and-exporting-content/craft-integration/craft-integration-step-2-template-mappings#supported-craft-fields) mapping GC fields to "Rich Text" fields in Craft, [Redactor](https://github.com/craftcms/redactor) fields are not selectable as targets in the map. I'm guessing this has something to do with "Rich Text" no longer being a built-in field type [as of 3.0.0-RC1](https://github.com/craftcms/cms/blob/master/CHANGELOG-v3.md#removed-7).

**Comment by evanwarner** [comment]
Indeed, the plugin source code still only refers to `craft\fields\RichText` and not to `craft\redactor\Field`.

**Comment by evanwarner** [comment]
Also note that [CKEditor](https://github.com/craftcms/ckeditor) is the other recommended rich-text replacement plugin.

**Comment by valery-solspace** [comment]
Thanks for your feedback! CKEditor and Redactor support is added in latest release.
